const images = {
    logo1: require('../assets/images/logo1.png'),
    logo2: require('../assets/images/logo2.png'),
    logo3: require('../assets/images/logo3.png'),
    logo4: require('../assets/images/logo4.png'),
    logo5: require('../assets/images/logo5.png'),
    backBtn: require('../assets/images/backbutton.png'),
    pancake: require('../assets/images/pancake.png'),
    level: require('../assets/images/level.png'),
    clock: require('../assets/images/clock.png'),
    salad: require('../assets/images/salad.png'),
    soup: require('../assets/images/soup.png'),
    tea: require('../assets/images/tea.png'),
    breakfast: require('../assets/images/breakfast.png'),
    user: require('../assets/images/user.png'),
    cake: require('../assets/images/cake.jpg'),
    drink: require('../assets/images/drink.jpg'),
    fastfood: require('../assets/images/fastfood.jpg'),
    healthy: require('../assets/images/healthy.jpeg'),
    italian: require('../assets/images/italian.jpg'),
    japanese: require('../assets/images/japanese.jpeg'),
    korean: require('../assets/images/korean.jpg'),
    maindish: require('../assets/images/maindish.jpg'),
    salad2: require('../assets/images/salad.jpg'),
    vegetarian: require('../assets/images/vegetarian.jpg'),
    vietnamese: require('../assets/images/vietnamese.jpg'),
}


export default images